### ISSUE TITLE
Autocompletion completes non-executable files

### ISSUE THREAD

**Issue by zph** [toumorokoshi/tome#15]
With the folder layout of:

```
script1
script2
non-executable-file
```

Autocomplete shows all of them.

Do we want to filter down to only things set as executable? Non-executables won't work when the exec happens and might be an invalid format like markdown.

Currently these are selected based on presence in folder and excluded if in ignore list, but we could potentially stat each one to find only the ones with `+x` set.

**Comment by toumorokoshi** [comment]
It's a good question. I think it makes sense to *not* show the file in completion, because:

- many shells will not complete to non-executable files.
- this affords a mechanism to include supporting files into the same directory (just don't mark them as executable).
- to your point, some files may not be executable, so don't try to execute them.

As long as we handle the edge case of no executable files in the directory, I think it's fine.

**Comment by toumorokoshi** [comment]
After reviewing a bit, I've landed for now on not adding this functionality. 

To help hide files, the user can prefix the file with a dot (`.`). This helps keeps the behavior easier to reason about to.

Happy to re-open if anyone feels differently and wants to discuss.
