### ISSUE TITLE
Contributing back to tome

### ISSUE THREAD

**Issue by zph** [toumorokoshi/tome#3]
👋 

Long time `sub` fan and found your project thanks to a friend. Thanks for setting up a new incarnation! I've setup a `sub` based cli at the last couple places I've worked and it's been great. Interested to play with tome and see if it's my new goto.

When trying to run the current HEAD of tome, I get a test failure:

```
bash-5.1$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/tome-2fa1d8bb501aff4b

running 16 tests
test commands::tests::test_should_not_source ... ok
test commands::tests::test_usage ... ok
test commands::tests::test_should_source ... ok
test commands::tests::test_help ... ok
test tests::test_dangerous_characters_quoted ... ok
test tests::test_script_directory_argument ... ok
test tests::test_directory_completion ... ok
test tests::test_script_in_directory ... ok
test tests::test_script_in_directory_not_found ... ok
test tests::test_root_directory_completion ... ok
test tests::test_simple_script ... ok
test tests::test_source ... ok
test tests::test_use_arg ... ok
test tests::test_help_page ... ok
test tests::test_simple_script_completion ... ok
test tests::test_source_completion ... FAILED

failures:

---- tests::test_source_completion stdout ----
thread 'tests::test_source_completion' panicked at 'assertion failed: `(left == right)`
  left: `Ok("")`,
 right: `Ok("foo baz\n")`', src/tests.rs:43:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_source_completion

test result: FAILED. 15 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s
```

I investigated this ~by setting up a script to recompile tome and prepend the compiled ./target/debug/tome` to my path (otherwise system tome would be used) and~ (edited due to my misunderstanding test harness) re-run the tests across the various git tags. In my testing this one test has failed from v0.1 onwards to v0.7.1.

A couple questions:
* Are you seeing different test results than I am?
* Is the desired behavior still that `source` style scripts allow for completion?
* If I'm hacking on this, would you appreciate things like Github Actions for CI and patches for that test failure?

**Comment by zph** [comment]
Update, I've been having fun hacking on it in my fork. If you're interested, I'm happy to contribute changes back :D <3.

**Comment by zph** [comment]
(Noticed I didn't tag you directly yet 😅, doing so now! @toumorokoshi )

**Comment by toumorokoshi** [comment]
Hi! Sorry about that, I need to look at my notification settings to see why I missed this the first time.

Thanks so much for looking into the issues! I do hope it can help fill the `sub` gap, but i know there a little work there.

I'm mobile so will reply more thoroughly on the morn, but if you have changes, awesome! Smaller changes are certainly easier, would you mind starting with a list as you suggested?

Thanks again for the interest and the offer to help!

**Comment by zph** [comment]
I've had odd experiences with GH notifications myself :).

I started small and modest on changes... then it got more involved. There's not an urgency on my side beyond interest and excitement in helping this project. I've implemented sub at my last two companies so this is a familiar problem space.

# Batch #1 changes (ie zph/tome#master)
- Adding fish shell autocomplete
- Using the mkdocs index.md as README.md via a symlink (avoid duplication and improve landing page info)
- Adding a homebrew recipe (https://github.com/zph/tome/blob/master/pkg/brew/tome.rb)
- I have fixes/suggestions from debugging `.cargo/config` when developing on OS X Big Sur and doing compilation for darwin and linux targets (darwin->darwin and darwin->linux)
- Github Actions for running tests and linting  (https://github.com/zph/tome/actions/runs/656589896)
- I hit a panic during `.unwrap()` when testing fish autocomplete, patched that.
- Rename final mentions of `cookbook` to `tome`

You can find most of those changes here https://github.com/zph/tome on my master branch.

## And then
Then... I got excited and made bigger changes! Partly it was liking learning more Rust. Partly it was driven by wanting to auto-generate the autocompletion by using an arg parsing library. I really enjoyed writing the Rust and envisioning what I want from `tome`. So even if these changes aren't your jam, I had fun.

# Batch 2 changes (ie zph/tome#use-clap)
- Use clap crate for arg parsing (https://github.com/clap-rs/clap). Clap made the cli interface declarative (https://github.com/zph/tome/blob/use-clap/src/main.rs#L10-L105)
- That gives consistent help output and suggestions, such as:
```
$ tome --help
tome 0.1.0
Yusuke Tsutsumi <yusuke@tsutsumi.io>


USAGE:
    tome [OPTIONS] [SUBCOMMAND]

FLAGS:
    -h, --help       Print help information
    -V, --version    Prints version information

OPTIONS:
    -v, --verbose <v>...    Sets the level of verbosity

SUBCOMMANDS:
    commands
    complete
    exec
    help        Prints this message or the help of the given subcommand(s)
    init
    init_v2
```

Or
```
$ tome init_v2 --help
USAGE:
    tome init_v2 <function_name> <directory> <shell>

ARGS:
    <function_name>    Function name
    <shell>            Shell for init
    <directory>        Directory of scripts

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

- Use clap_generate for autogenerating shell autocomplete.
- Shift interface away from using `tome ./example --complete dir_exam<TAB>` to `tome complete --directory ./example dir_exam<TAB>`. Then other subcommands are `init | exec | complete | commands`. Using clap+subcommands simplifies some of the internal logic around argparsing.
- Allowing for help and summary to be parsed when script uses commenting delimiter other than `#`
- Instead of passing back errors via `echo -e` and fighting the shell escaping, print those via `eprintln`. By sending all error/notice info to stderr we can still execute scripts via the `eval ...` when using `eprintln`
- In order to debug areas, I put in some `log::debug!` statements, I can easily remove them or leave them for optional debugging when setting `RUST_LOG=debug`. In normal use they're not printed.

Clap crate usage is implemented, autogenerating fish shell completions is 95% complete, bash, zsh, elvish, powershell are 80% (ie they are autogenerated but need extra logic to finish off).

The second larger set of interface changes are here: https://github.com/zph/tome/commits/use-clap.

# Disclaimers

I have solid programming experience but almost none in Rust. I've read the Rust book by Nichols and Klabnick and I've spent 3 days coding Rust in this project. My programming background is in Elixir, Python, Golang, Clojure and Bash.

# Conclusion

My expectation is Batch #1 of changes are minor and easy to integrate. Batch #2 makes sense if you like them also, but I don't want to impose my vision of `tome` on you :). If those sound good, let's agree on it and then I'll work towards polishing and verifying them and then contribute upstream.

**Comment by toumorokoshi** [comment]
Cool! Thanks for typing all that out, it's helpful. And I want to say this is AWESOME! I'm very passionate about the sub-style subcommands too, so happy to collaborate with someone who shares that sentiment.

## Review of 1/2

High level batches 1 and 2 are welcome. 

If you can file a PR for 1 that would be great (have a couple minor comments but I figure we address that in the PR).

For 2, most of your changes seem like they're good quality-of-life improvements. The following could be batched in 1 if you prefer:

* Allowing for help and summary to be parsed when script uses commenting delimiter other than #
* Instead of passing back errors via echo -e and fighting the shell escaping, print those via eprintln. By sending all error/notice info to stderr we can still execute scripts via the eval ... when using eprintln
* In order to debug areas, I put in some log::debug! statements, I can easily remove them or leave them for optional debugging when setting RUST_LOG=debug. In normal use they're not printed.

That last one is the argparsing / clap one. The changes you've made (especially the result of a clear help message with consistent argparse behavior) are a huge improvement.

The only reason I'd like to review a bit more is to make sure I understand all the ramifications. Also, if we're going to re-do argparsing, I'd love to see if it's compatible with some ideas I had for tome but didn't get around to (an easy way to search through all commands)

## Disclaimers

I'm not much of a rustacean myself, just like the language :) My biggest Rust project is a [hobby programming language](https://gitlab.com/tsutsumi.yusuke/disp). Nothing running in production, so to speak. 

## Conclusion

Just as a summary of my review of 1 / 2 above:

* PR for batch 1 would be great, should be easy to merge in, no concerns philosophically.
* batch 2 could be split into clap-related changes and non-clap changes. but if it's easier one PR is fine.
   * non-clap changes are similar to batch 1: no major review and let's merge it in.
   * claps changes want to review the CLI / commands. But overall the direction sounds great.

**Comment by zph** [comment]
I'll try and see how much work it is to parse Batch #2 into Batch #2.1 and 2.2. That would be cleaner and nicer depending on the lift.

**Comment by zph** [comment]
Thank you for the time and consideration in your response 👯

**Comment by toumorokoshi** [comment]
renaming this thread to the broader topic of collaboration and throwing ideas around. making an issue for the test failures (#6) so we can try to get to the bottom of it separately.
