### ISSUE TITLE
wish: support _SUB_ROOT like `sub`

### ISSUE THREAD

**Issue by markstos** [toumorokoshi/tome#41]
One feature from `sub` I don't see here is that `sub` provides to scripts an environment variable containing the "root" directory of the project. 

It's documented here in the README:
https://github.com/qrush/sub/blob/4bcb94f0c14f911fc77ac642318c5d19b359c5cd/README.md?plain=1#L58

So, if a project is named `rush`, an environment variable named `_RUSH_ROOT` would be set.  

Since compatibility with `sub` seems to be a goal, it would be nice to support this, or document the recommended refactoring for people converting scripts.

**Comment by toumorokoshi** [comment]
Hey! I think this is reasonable. It seems like it's best as a part of the output returned by init? I was originally thinking of just exporting as part of the `command-execute`, but that seems more complex that it needs to be and wouldn't make the variable available outside of invocations of tome.

**Comment by markstos** [comment]
I would rather have it as part of command-execute, which relates to my interest in not relying on how the environment is configured (see #40). So let's resolve the conversation in #40 and then come back to this thread.

**Comment by toumorokoshi** [comment]
now that #44 is closed, I think we can talk about this issue.

I was looking at implementing it: the one thing is the variable name (e.g. `_sub_root`) in sub is dependent on what the command was actually called. Since `tome run` doesn't take in a command name, it won't be able to generate that time.

how about a constant like `_TOME_SCRIPT_ROOT`? I can't think of a good case off the top of my head to need to include the command name in the environment variable.

**Comment by toumorokoshi** [comment]
Fixed and shipped in https://github.com/toumorokoshi/tome/releases/tag/v0.11.0. Thanks!
